/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import clases.Cliente;
import clases.Helper;
import clases.Trabajador;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author gcoronad2
 */
public class AgregarCliente extends javax.swing.JDialog {
    /**
     * Creates new form Agregar
     */
    String rutaC, rutaT;
    ObjectOutputStream salida;
    LinkedList<Cliente> clientes;
    int aux = 0;
    public AgregarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JButton botonesH[]={cmdBuscar, cmdGuardar, cmdCancelar};
        JButton botonesD[]={cmdEliminar};
        rutaC = "src/datos/clientes.txt";
        rutaT = "src/datos/trabajadores.txt";
        Helper.llenarComboTrabajadores(cmbEncargado, rutaT);
        try {
            clientes = Helper.traerDatos(rutaT);
            salida = new ObjectOutputStream(new FileOutputStream(rutaC));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, clientes);
        Helper.llenarTablaClientes(tblClientes, rutaC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbEncargado = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtNumTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumTelFiador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtDeuda = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCancelar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AGREGAR CLIENTES");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Cliente:"));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Cédula:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 37, -1, -1));

        txtCc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCcKeyTyped(evt);
            }
        });
        jPanel2.add(txtCc, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 30, 140, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 81, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 75, 140, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Deuda:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 27));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Sexo:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 140, 27));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Teléfono:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 81, -1, -1));

        jPanel2.add(cmbEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 140, 27));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Dirección:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 37, -1, -1));

        txtNumTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumTelKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 75, 140, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Apellido:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 125, -1, -1));

        txtNumTelFiador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumTelFiadorKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumTelFiador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 140, 27));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Encargado:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino", "Indefinido" }));
        jPanel2.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 27));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Teléfono (fiador):");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 125, -1, -1));

        txtDeuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeudaKeyTyped(evt);
            }
        });
        jPanel2.add(txtDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 160, 27));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 520, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opciones"));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        cmdEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        cmdGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 30));

        cmdBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 130, 250));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Clientes"));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Deuda", "Teléfono2", "Encargado", "Cédula", "Nombre", "Apeliido", "Dirección", "Teléfono1", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 760, 250));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 780, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(814, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        // TODO add your handling code here:
        int i, op;
        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar a este cliente?", "ELIMINAR", JOptionPane.YES_NO_OPTION);
        clientes = Helper.traerDatos(rutaC);
        if (op == JOptionPane.YES_OPTION) {
            i = tblClientes.getSelectedRow();
            clientes.remove(i);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(rutaT));
            } catch (FileNotFoundException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
            Helper.volcado(salida, clientes);
            Helper.llenarTablaClientes(tblClientes, rutaC);
            txtCc.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtAddress.setText("");
            txtNumTel.setText("");
            txtNumTelFiador.setText("");
            txtDeuda.setText("");
            cmbEncargado.setSelectedIndex(0);
            cmbSexo.setSelectedIndex(0);
            txtCc.requestFocusInWindow();
            JButton botonesH[]={cmdBuscar,cmdCancelar};
            JButton botonesD[]={cmdEliminar,cmdGuardar};
            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        }
        
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        // TODO add your handling code here:
        String deuda, cc, nombre, apellido, address, num_tel, num_tel_fiador, sexo, auxEncargado, ccEncargado;
        Trabajador encargado;
        int indice;
        deuda = txtDeuda.getText();
        cc = txtCc.getText();
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        address = txtAddress.getText();
        num_tel = txtNumTel.getText();
        num_tel_fiador = txtNumTelFiador.getText();
        sexo = cmbSexo.getSelectedItem().toString();
        auxEncargado = cmbEncargado.getSelectedItem().toString();
        indice = auxEncargado.indexOf("-") - 1;
        ccEncargado = auxEncargado.substring(0, indice);
        LinkedList<Cliente> clientesModificado;
        encargado = Helper.traerTrabajadorCedula(ccEncargado, rutaT);
        /*if (cc.equals(Helper.traerPersonaCedula(cc, ruta).getCc())) {
                Helper.mensaje(this, "Ya existe con esta cédula.", 3);
        }*/
        try {
            if (aux == 0) {
                Cliente c = new Cliente(deuda, num_tel_fiador, encargado, cc, nombre, apellido, address, num_tel, sexo);
                c.guardar(salida);
            }
            else {
                clientesModificado = Helper.modificarCliente(rutaC, deuda, num_tel_fiador, encargado, cc, nombre, apellido, address, num_tel, sexo);
                salida = new ObjectOutputStream(new FileOutputStream(rutaC));
                Helper.volcado(salida, clientesModificado);
                aux = 0;
                Helper.mensaje(this, "Cliente actualizado correctamente.", 1);
            }
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.llenarTablaClientes(tblClientes, rutaC);
        txtCc.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtAddress.setText("");
        txtNumTel.setText("");
        txtNumTelFiador.setText("");
        txtDeuda.setText("");
        cmbEncargado.setSelectedIndex(0);
        cmbSexo.setSelectedIndex(0);
        txtCc.requestFocusInWindow();
        JButton botonesH[]={cmdBuscar,cmdCancelar};
        JButton botonesD[]={cmdEliminar,cmdGuardar};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        // TODO add your handling code here:
        txtCc.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtAddress.setText("");
        txtNumTel.setText("");
        txtNumTelFiador.setText("");
        txtDeuda.setText("");
        cmbEncargado.setSelectedIndex(0);
        cmbSexo.setSelectedIndex(0);
        txtCc.requestFocusInWindow();
        JButton botonesH[]={cmdBuscar,cmdCancelar};
        JButton botonesD[]={cmdEliminar,cmdGuardar};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // TODO add your handling code here:
        int i;
        String auxEncargado;
        Cliente c;
        Trabajador encargado;
        clientes = Helper.traerDatos(rutaC);
        i = tblClientes.getSelectedRow();
        c = clientes.get(i);
        txtCc.setText(c.getCc());
        txtNombre.setText(c.getNombre());
        txtApellido.setText(c.getApellido());
        txtAddress.setText(c.getAddress());
        txtNumTel.setText(c.getNum_tel());
        txtNumTelFiador.setText(c.getNum_tel_fiador());
        txtDeuda.setText(c.getDeuda());
        encargado = c.getEncargado();
        auxEncargado = encargado.getCc() + " - " + encargado.getNombre() + " " + encargado.getApellido();
        cmbEncargado.setSelectedItem(auxEncargado);
        cmbSexo.setSelectedItem(c.getSexo());
        aux = 1;
        JButton botonesH[]={cmdEliminar,cmdGuardar,cmdCancelar};
        JButton botonesD[]={cmdBuscar};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_tblClientesMouseClicked

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        // TODO add your handling code here:
        if (txtCc.getText().isEmpty()) {
            Helper.mensaje(this, "Ingrese una cédula.", 3);
        }
        String cc, auxEncargado;
        Trabajador encargado;
        cc = txtCc.getText();
        Cliente c;
        if (Helper.buscarClienteCedula(cc, rutaC)) {
            c = Helper.traerClienteCedula(cc, rutaC);
            txtNombre.setText(c.getNombre());
            txtApellido.setText(c.getApellido());
            txtAddress.setText(c.getAddress());
            txtNumTel.setText(c.getNum_tel());
            encargado = c.getEncargado();
            auxEncargado = encargado.getCc() + " - " + encargado.getNombre() + " " + encargado.getApellido();
            cmbEncargado.setSelectedItem(auxEncargado);
            cmbSexo.setSelectedItem(c.getSexo());
            aux = 1;
        }
        else {
            txtNombre.requestFocusInWindow();
            aux = 0;
        }
        JButton botonesH[]={cmdGuardar,cmdCancelar, cmdEliminar};
        JButton botonesD[]={cmdBuscar};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void txtCcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCcKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
        if(!Character.isDigit(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_txtCcKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
        if(Character.isDigit(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
        if(Character.isDigit(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
        if(!Character.isDigit(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_txtAddressKeyTyped

    private void txtNumTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTelKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
        if(!Character.isDigit(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_txtNumTelKeyTyped

    private void txtNumTelFiadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumTelFiadorKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); 
        if(!Character.isDigit(c)) { 
            getToolkit().beep(); 
            evt.consume(); 
        } 
    }//GEN-LAST:event_txtNumTelFiadorKeyTyped

    private void txtDeudaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeudaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeudaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarCliente dialog = new AgregarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbEncargado;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCc;
    private javax.swing.JTextField txtDeuda;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumTel;
    private javax.swing.JTextField txtNumTelFiador;
    // End of variables declaration//GEN-END:variables
}
