/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;

/**
 *
 * @author rmorales1
 */
public class CantidadClientes extends javax.swing.JDialog {

    /**
     * Creates new form Agregar
     */
    String rutaC;
    public CantidadClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rutaC = "src/datos/clientes.txt";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmdOk = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        chkI = new javax.swing.JCheckBox();
        chkF = new javax.swing.JCheckBox();
        chkM = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TRABAJADORES");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CANTIDAD DE CLIENTES INGRESADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok_list.png"))); // NOI18N
        cmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOkActionPerformed(evt);
            }
        });
        jPanel2.add(cmdOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 170, 32));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkI.setText("I");
        chkI.setOpaque(false);
        jPanel3.add(chkI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 40, 30));

        chkF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkF.setText("F");
        chkF.setOpaque(false);
        jPanel3.add(chkF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 40, 30));

        chkM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkM.setText("M");
        chkM.setOpaque(false);
        jPanel3.add(chkM, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Sexo:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 170, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 320, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(376, 277));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOkActionPerformed
        // TODO add your handling code here:
        String cant;
        if (chkM.isSelected() && chkF.isSelected() && chkI.isSelected()) {
            cant = Helper.cantidadClientes(rutaC, "Masculino", "Femenino", "Indefinido");
            Helper.mensaje(this, cant, 1);
        }
        else if (chkM.isSelected() && chkF.isSelected()) {
            cant = Helper.cantidadClientes(rutaC, "Masculino", "Femenino");
            Helper.mensaje(this, cant, 1);
        }
        else if (chkM.isSelected() && chkI.isSelected()) {
            cant = Helper.cantidadClientes(rutaC, "Masculino", "Indefinido");
            Helper.mensaje(this, cant, 1);
        }
        else if (chkF.isSelected() && chkI.isSelected()) {
            cant = Helper.cantidadClientes(rutaC, "Femenino", "Indefinido");
            Helper.mensaje(this, cant, 1);
        }
        else if (chkM.isSelected()) {
            cant = Helper.cantidadClientes(rutaC, "Masculino");
            Helper.mensaje(this, cant, 1);
        }
        else if (chkF.isSelected()) {
            cant = Helper.cantidadClientes(rutaC, "Femenino");
            Helper.mensaje(this, cant, 1);
        }
        else {
            cant = Helper.cantidadClientes(rutaC, "Indefinido");
            Helper.mensaje(this, cant, 1);
        }
        
    }//GEN-LAST:event_cmdOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CantidadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CantidadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CantidadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CantidadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CantidadClientes dialog = new CantidadClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkF;
    private javax.swing.JCheckBox chkI;
    private javax.swing.JCheckBox chkM;
    private javax.swing.JButton cmdOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
