/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import clases.Helper;
import clases.Persona;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author gcoronad2
 */
public class Modificar extends javax.swing.JDialog {

    /**
     * Creates new form Modificar
     */
    String ruta;
    ObjectOutputStream salida;
    ArrayList<Persona> personas;
    public Modificar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ruta = "src/datos/people.txt";
        try {
            personas = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcado(salida, personas);
        for (int i = 0; i < personas.size(); i++) {
            cmbClientes.addItem(personas.get(i).getCc());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbClientes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApeliido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDeuda = new javax.swing.JTextField();
        cmdModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNuevoValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNuevaDeuda = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClientesItemStateChanged(evt);
            }
        });
        cmbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbClientesMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbClientesMouseReleased(evt);
            }
        });
        jPanel1.add(cmbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 30));

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtNombre.setEditable(false);
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, 30));

        jLabel2.setText("Cédula del cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtApeliido.setEditable(false);
        jPanel1.add(txtApeliido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 150, 30));

        jLabel4.setText("Deuda actual:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtDeuda.setEditable(false);
        jPanel1.add(txtDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 130, 30));

        cmdModificar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdModificar.setText("Modificar");
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 130, 30));

        jLabel5.setText("Nuevo valor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        jPanel1.add(txtNuevoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 130, 30));

        jLabel6.setText("NUEVA DEUDA:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        txtNuevaDeuda.setEditable(false);
        jPanel1.add(txtNuevaDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 130, 30));

        cmbOperacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agregar", "Restar" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(468, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        // TODO add your handling code here:
        //long deuda;
        
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClientesMouseClicked

    private void cmbClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbClientesMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbClientesMouseReleased

    private void cmbClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbClientesMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbClientesMouseExited

    private void cmbClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClientesItemStateChanged
        // TODO add your handling code here:
        for (int i = 0; i <= cmbClientes.getSelectedIndex(); i++) {
            txtNombre.setText(personas.get(i).getNombre());
            txtApeliido.setText(personas.get(i).getApellido());
            txtDeuda.setText(personas.get(i).getDeuda());
        }
    }//GEN-LAST:event_cmbClientesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modificar dialog = new Modificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbClientes;
    private javax.swing.JComboBox cmbOperacion;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApeliido;
    private javax.swing.JTextField txtDeuda;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNuevaDeuda;
    private javax.swing.JTextField txtNuevoValor;
    // End of variables declaration//GEN-END:variables
}
