/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author gcoronad2
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOpciones = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();
        mnTrabajador = new javax.swing.JMenu();
        mnAgregarTrabajador = new javax.swing.JMenuItem();
        mnListadoCompletoTrabajador = new javax.swing.JMenuItem();
        mnCliente = new javax.swing.JMenu();
        mnAgregarCliente = new javax.swing.JMenuItem();
        mnReportes = new javax.swing.JMenu();
        mnListadoPorSexo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL DE DEUDAS");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portada.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(255, 204, 204));

        mnOpciones.setText("Opciones");
        mnOpciones.add(jSeparator1);

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        mnOpciones.add(mnSalir);

        jMenuBar1.add(mnOpciones);

        mnTrabajador.setText("Trabajadores");

        mnAgregarTrabajador.setText("Agregar");
        mnAgregarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarTrabajadorActionPerformed(evt);
            }
        });
        mnTrabajador.add(mnAgregarTrabajador);

        mnListadoCompletoTrabajador.setText("Listado Completo");
        mnListadoCompletoTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListadoCompletoTrabajadorActionPerformed(evt);
            }
        });
        mnTrabajador.add(mnListadoCompletoTrabajador);

        jMenuBar1.add(mnTrabajador);

        mnCliente.setText("Clientes");

        mnAgregarCliente.setText("Agregar");
        mnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarClienteActionPerformed(evt);
            }
        });
        mnCliente.add(mnAgregarCliente);

        jMenuBar1.add(mnCliente);

        mnReportes.setText("Reportes");

        mnListadoPorSexo.setText("Listado Por Sexo");
        mnListadoPorSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListadoPorSexoActionPerformed(evt);
            }
        });
        mnReportes.add(mnListadoPorSexo);

        jMenuBar1.add(mnReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(666, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnListadoCompletoTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListadoCompletoTrabajadorActionPerformed
        // TODO add your handling code here:
        ListadoCompletoTrabajador lct = new ListadoCompletoTrabajador(this,true);
        lct.setVisible(true);
    }//GEN-LAST:event_mnListadoCompletoTrabajadorActionPerformed

    private void mnListadoPorSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListadoPorSexoActionPerformed
        // TODO add your handling code here:
        ListadoPorSexo lps = new ListadoPorSexo(this,true);
        lps.setVisible(true);
    }//GEN-LAST:event_mnListadoPorSexoActionPerformed

    private void mnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarClienteActionPerformed
        // TODO add your handling code here:
        AgregarCliente ac = new AgregarCliente(this, true);
        ac.setVisible(true);
    }//GEN-LAST:event_mnAgregarClienteActionPerformed

    private void mnAgregarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarTrabajadorActionPerformed
        // TODO add your handling code here:
        AgregarTrabajador at = new AgregarTrabajador(this, true);
        at.setVisible(true);
    }//GEN-LAST:event_mnAgregarTrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JMenuItem mnAgregarCliente;
    private javax.swing.JMenuItem mnAgregarTrabajador;
    private javax.swing.JMenu mnCliente;
    private javax.swing.JMenuItem mnListadoCompletoTrabajador;
    private javax.swing.JMenuItem mnListadoPorSexo;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenu mnReportes;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenu mnTrabajador;
    // End of variables declaration//GEN-END:variables
}
